-- Create interactions tables

-- Mutes table
CREATE TABLE IF NOT EXISTS mutes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    muter TEXT NOT NULL,
    muted_user TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(muter, muted_user)
);

-- Blocks table
CREATE TABLE IF NOT EXISTS blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker TEXT NOT NULL,
    blocked_user TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(blocker, blocked_user)
);

-- Not Interested table
CREATE TABLE IF NOT EXISTS not_interested (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_address TEXT NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_address, post_id)
);

-- Add RLS policies if needed (assuming public access for now or handled by service role)
ALTER TABLE mutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE not_interested ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone (or restrict as needed)
CREATE POLICY "Allow public read access to mutes" ON mutes FOR SELECT USING (true);
CREATE POLICY "Allow public read access to blocks" ON blocks FOR SELECT USING (true);
CREATE POLICY "Allow public read access to not_interested" ON not_interested FOR SELECT USING (true);

-- Allow authenticated users to insert (adjust as needed)
CREATE POLICY "Allow authenticated insert to mutes" ON mutes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated insert to blocks" ON blocks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated insert to not_interested" ON not_interested FOR INSERT WITH CHECK (true);
